// priority: 0

StartupEvents.registry('item', e => {
  // The texture for this item has to be placed in kubejs/assets/kubejs/textures/item/test_item.png
  // If you want a custom item model, you can create one in Blockbench and put it in kubejs/assets/kubejs/models/item/test_item.json
  e.create('incomplete_rail')

  //e.create('tattered_elytra').tooltip('Maybe it can be fixed...')

  e.create('crushed_raw_cobalt')

  e.create('ignitium_nugget').rarity('EPIC')

  e.create('witherite_nugget').rarity('EPIC')

  e.create('soul_of_flight').rarity('RARE').tooltip('The essence of powerful flying creatures')

  e.create('wither_ashes').rarity('EPIC')

  e.create('crushed_raw_thallasium')
})

ItemEvents.modification(event => {
  function fastitem(fastInput) {
    event.modify(fastInput, item => {
      item.overrideFood(food => {
        food.fastToEat()
        food.alwaysEdible()
      })
    })
  }

  fastitem('alexscaves:sweetish_fish_red')
  fastitem('alexscaves:sweetish_fish_green')
  fastitem('alexscaves:sweetish_fish_yellow')
  fastitem('alexscaves:sweetish_fish_blue')
  fastitem('alexscaves:sweetish_fish_pink')
  fastitem('alexscaves:gelatin_red')
  fastitem('alexscaves:gelatin_green')
  fastitem('alexscaves:gelatin_yellow')
  fastitem('alexscaves:gelatin_blue')
  fastitem('alexscaves:gelatin_pink')
  fastitem('alexscaves:peppermint_powder')
  fastitem('alexscaves:gumball_pile')
  fastitem('alexscaves:caramel')
  fastitem('alexscaves:gingerbread_crumbs')
  fastitem('alexscaves:block_of_chocolate')
  fastitem('alexscaves:block_of_polished_chocolate')
  fastitem('alexscaves:block_of_frosted_chocolate')
  fastitem('alexscaves:block_of_frosting')
  fastitem('alexscaves:block_of_vanilla_frosting')
  fastitem('alexscaves:block_of_chocolate_frosting')
  fastitem('alexscaves:sweet_puff')
  fastitem('alexscaves:cake_layer')
  fastitem('alexscaves:cookie_block')
  fastitem('alexscaves:dough_block')
  fastitem('alexscaves:wafer_cookie_block')
  fastitem('alexscaves:wafer_cookie_stairs')
  fastitem('alexscaves:wafer_cookie_slab')
  fastitem('alexscaves:wafer_cookie_wall')
  fastitem('alexscaves:licoroot')
  fastitem('alexscaves:licoroot_vine')
  fastitem('alexscaves:licoroot_sprout')
  fastitem('alexscaves:small_peppermint')
  fastitem('alexscaves:large_peppermint')
  fastitem('alexscaves:vanilla_ice_cream')
  fastitem('alexscaves:chocolate_ice_cream')
  fastitem('alexscaves:sweetberry_ice_cream')
  fastitem('alexscaves:sprinkles')
  fastitem('alexscaves:giant_sweetberry')
  fastitem('alexscaves:candy_cane')
  fastitem('alexscaves:candy_cane_block')
  fastitem('alexscaves:chiseled_candy_cane_block')
  fastitem('alexscaves:stripped_candy_cane_block')
  fastitem('alexscaves:candy_cane_pole')
  fastitem('alexscaves:stripped_candy_cane_pole')
  fastitem('alexscaves:lollipop_bunch')
  fastitem('alexscaves:frostmint')
  fastitem('alexscaves:sugar_glass')
  fastitem('alexscaves:sundrop')
  fastitem('alexscaves:gummy_ring_red')
  fastitem('alexscaves:gummy_ring_green')
  fastitem('alexscaves:gummy_ring_yellow')
  fastitem('alexscaves:gummy_ring_blue')
  fastitem('alexscaves:gummy_ring_pink')
  fastitem('alexscaves:rock_candy_white')
  fastitem('alexscaves:rock_candy_orange')
  fastitem('alexscaves:rock_candy_magenta')
  fastitem('alexscaves:rock_candy_light_blue')
  fastitem('alexscaves:rock_candy_yellow')
  fastitem('alexscaves:rock_candy_lime')
  fastitem('alexscaves:rock_candy_pink')
  fastitem('alexscaves:rock_candy_gray')
  fastitem('alexscaves:rock_candy_light_gray')
  fastitem('alexscaves:rock_candy_cyan')
  fastitem('alexscaves:rock_candy_purple')
  fastitem('alexscaves:rock_candy_blue')
  fastitem('alexscaves:rock_candy_brown')
  fastitem('alexscaves:rock_candy_green')
  fastitem('alexscaves:rock_candy_red')
  fastitem('alexscaves:rock_candy_black')
  fastitem('alexscaves:gingerbread_block')
  fastitem('alexscaves:gingerbread_stairs')
  fastitem('alexscaves:gingerbread_slab')
  fastitem('alexscaves:gingerbread_wall')
  fastitem('alexscaves:gingerbread_door')
  fastitem('alexscaves:gingerbarrel')
  fastitem('alexscaves:frosted_gingerbread_block')
  fastitem('alexscaves:frosted_gingerbread_stairs')
  fastitem('alexscaves:frosted_gingerbread_slab')
  fastitem('alexscaves:frosted_gingerbread_wall')
  fastitem('alexscaves:frosted_gingerbread_door')
  fastitem('alexscaves:gingerbread_bricks')
  fastitem('alexscaves:gingerbread_brick_stairs')
  fastitem('alexscaves:gingerbread_brick_slab')
  fastitem('alexscaves:gingerbread_brick_wall')
  fastitem('alexscaves:frosted_gingerbread_bricks')
  fastitem('alexscaves:frosted_gingerbread_brick_stairs')
  fastitem('alexscaves:frosted_gingerbread_brick_slab')
  fastitem('alexscaves:frosted_gingerbread_brick_wall')
  //fastitem('alexscaves:jelly_bean')

  fastitem('create:bar_of_chocolate')
})

StartupEvents.registry('fluid', e => {
  // Basic "thick" (looks like lava) fluid with red tint

  e.create('lavender_tea')
      .thinTexture(0xFBAED2)
      .bucketColor(0xFBAED2)
      .displayName('Lavender Tea')
      .noBucket()
      .noBlock()

  e.create('ginger_tea')
      .thinTexture(0xEF9F59)
      .bucketColor(0xEF9F59)
      .displayName('Ginger Tea')
      .noBucket()
      .noBlock()

  e.create('passion_aloe_nectar')
      .thinTexture(0xFDBE02)
      .bucketColor(0xFDBE02)
      .displayName('Passion Aloe Nectar')
      .noBucket()
      .noBlock()

  e.create('cherry_cream_soda')
      .thickTexture(0xFE8296)
      .bucketColor(0xFE8296)
      .displayName('Cherry Cream Soda')
      .noBucket()
      .noBlock()

  e.create('pickerelweed_juice')
      .thinTexture(0x40E0D0)
      .bucketColor(0x40E0D0)
      .displayName('Pickerelweed Juice')
      .noBucket()
      .noBlock()

  // Crabber's Delight coconut milk
  // texture derived from bubble tea in Create Central Kitchen
  e.create('coconut_milk')
    .displayName('Coconut Milk')
    .stillTexture('kubejs:fluid/coconut_milk_still')
    .flowingTexture('kubejs:fluid/coconut_milk_flowing')
    .bucketColor(0xF1F0EE)
    .density(2000)
    .viscosity(2000)
    .temperature(0)

  e.create('fish_oil')
      .thinTexture(0xEBBE65)
      .bucketColor(0xEBBE65)
      .displayName('Fish Oil')
      .noBucket()
      .noBlock()

  // liquid dyes
  e.create('white_dye')
      .thinTexture(0xF9FFFE)
      .bucketColor(0xF9FFFE)
      .displayName('White Dye')
      .noBlock()

  e.create('light_gray_dye')
      .thinTexture(0x9D9D97)
      .bucketColor(0x9D9D97)
      .displayName('Light Gray Dye')
      .noBlock()

  e.create('gray_dye')
      .thinTexture(0x474F52)
      .bucketColor(0x474F52)
      .displayName('Gray Dye')
      .noBlock()

  e.create('black_dye')
      .thinTexture(0x1D1D21)
      .bucketColor(0x1D1D21)
      .displayName('Black Dye')
      .noBlock()

  e.create('brown_dye')
      .thinTexture(0x835432)
      .bucketColor(0x835432)
      .displayName('Brown Dye')
      .noBlock()

  e.create('red_dye')
      .thinTexture(0xB02E26)
      .bucketColor(0xB02E26)
      .displayName('Red Dye')
      .noBlock()

  e.create('orange_dye')
      .thinTexture(0xF9801D)
      .bucketColor(0xF9801D)
      .displayName('Orange Dye')
      .noBlock()

  e.create('yellow_dye')
      .thinTexture(0xFED83D)
      .bucketColor(0xFED83D)
      .displayName('Yellow Dye')
      .noBlock()

  e.create('lime_dye')
      .thinTexture(0x80C71F)
      .bucketColor(0x80C71F)
      .displayName('Lime Dye')
      .noBlock()

  e.create('green_dye')
      .thinTexture(0x5E7C16)
      .bucketColor(0x5E7C16)
      .displayName('Green Dye')
      .noBlock()

  e.create('cyan_dye')
      .thinTexture(0x169C9C)
      .bucketColor(0x169C9C)
      .displayName('Cyan Dye')
      .noBlock()

  e.create('light_blue_dye')
      .thinTexture(0x3AB3DA)
      .bucketColor(0x3AB3DA)
      .displayName('Light Blue Dye')
      .noBlock()

  e.create('blue_dye')
      .thinTexture(0x3C44AA)
      .bucketColor(0x3C44AA)
      .displayName('Blue Dye')
      .noBlock()

  e.create('purple_dye')
      .thinTexture(0x8932B8)
      .bucketColor(0x8932B8)
      .displayName('Purple Dye')
      .noBlock()

  e.create('magenta_dye')
      .thinTexture(0xC74EBD)
      .bucketColor(0xC74EBD)
      .displayName('Magenta Dye')
      .noBlock()

  e.create('pink_dye')
      .thinTexture(0xF38BAA)
      .bucketColor(0xF38BAA)
      .displayName('Pink Dye')
      .noBlock()
})
